services:
  postgres:
    image: postgres:16
    container_name: postgres-users
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_users:/var/lib/postgresql/data
    networks:
      - usernet
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
  redis:
    image: redis:8.2.3
    container_name: redis-users
    restart: unless-stopped
    ports:
      - "6379:6379"           # expose sur l'hôte (optionnel si vous n'en avez pas besoin)
    volumes:
      - redis-data:/data      # persistance des données
    command: [ "redis-server"]
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "changeme", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - usernet

  user-service:
    build: .
    container_name: user-service
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      DATABASE_HOST: postgres-users
      DATABASE_PORT: 5432
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      KAFKA_HOST: kafka
      KAFKA_PORT: 9092

      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    networks:
      - usernet
#  kafka:
#    image: confluentinc/cp-kafka:7.5.0
#    hostname: kafka
#    container_name: kafka
#    ports:
#      - "9092:9092"
#      - "9101:9101"
#    environment:
#      CLUSTER_ID: "o0oqgfJkSRKy30HkVsAjBg"
#      KAFKA_NODE_ID: 1
#      KAFKA_PROCESS_ROLES: "broker,controller"
#      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:29093"
#      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
#      KAFKA_LISTENERS: "PLAINTEXT://kafka:29092,PLAINTEXT_HOST://0.0.0.0:9092,CONTROLLER://kafka:29093"
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT"
#      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:29092,PLAINTEXT_HOST://kafka:9092"
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
#      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
#      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
#      KAFKA_JMX_PORT: 9101
#      KAFKA_JMX_HOSTNAME: kafka
#      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
#    healthcheck:
#      test: kafka-broker-api-versions --bootstrap-server kafka:9092 || exit 1
#      interval: 10s
#      timeout: 10s
#      retries: 5
#    networks:
#      - usernet

  kafka:
    image: apache/kafka:latest
    container_name: broker
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
    networks:
      - usernet

networks:
  usernet:
#    driver: bridge
    external: true
volumes:
  postgres_data_users:
  redis-data:
